
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * @param {Function} fetchSongLyrics
 */
async function runAllFetches(currLinksList , fetchSongLyrics) {
  for (const link of currLinksList) {
    
    const randomDelay = Math.floor(Math.random() * 12001) + 3000;

    await fetchSongLyrics(link.url);

    await delay(randomDelay);
  }
}

// Todo import from separate data file
const fullAZLyricsLinks = [
    // Fixed links 
  { artist: "The Beatles", song: "Hey Jude", url: "https://www.azlyrics.com/lyrics/beatles/heyjude.html" }, 
  { artist: "Mark Ronson & Bruno Mars", song: "Uptown Funk", url: "https://www.azlyrics.com/lyrics/markronson/uptownfunk.html" }, 
  { artist: "The Weeknd", song: "Blinding Lights", url: "https://www.azlyrics.com/lyrics/weeknd/blindinglights.html" }, 
  { artist: "The Weeknd", song: "Save Your Tears", url: "https://www.azlyrics.com/lyrics/weeknd/saveyourtears.html" },
  { artist: "The Weeknd", song: "Starboy", url: "https://www.azlyrics.com/lyrics/weeknd/starboy.html" },
  { artist: "The Weeknd", song: "The Hills", url: "https://www.azlyrics.com/lyrics/weeknd/thehills.html" },
  { artist: "The Weeknd", song: "Can't Feel My Face", url: "https://www.azlyrics.com/lyrics/weeknd/cantfeelmyface.html" },
  { artist: "Lou Bega", song: "Mambo No. 5 (A Little Bit Of...)", url: "https://www.azlyrics.com/lyrics/loubega/mambono5.html" },
  { artist: "Whitney Houston", song: "I Wanna Dance With Somebody (Who Loves Me)", url: "https://www.azlyrics.com/lyrics/whitneyhouston/iwannadancewithsomebody.html" }, 
  { artist: "The Verve", song: "Bitter Sweet Symphony", url: "https://www.azlyrics.com/lyrics/verve/bittersweetsymphony.html" }, 
  { artist: "The Weeknd", song: "I Feel It Coming", url: "https://www.azlyrics.com/lyrics/weeknd/ifeelitcoming.html" }, 
  { artist: "The Who", song: "Baba O'Riley", url: "https://www.azlyrics.com/lyrics/who/babaoriley.html" },
  { artist: "Green Day", song: "Good Riddance (Time Of Your Life)", url: "https://www.azlyrics.com/lyrics/greenday/goodriddance.html" }, 
  { artist: "ABBA", song: "Gimme! Gimme! Gimme! (A Man After Midnight)", url: "https://www.azlyrics.com/lyrics/abba/gimmegimmegimme.html" }, 
  { artist: "The Weeknd", song: "Die For You", url: "https://www.azlyrics.com/lyrics/weeknd/dieforyou.html" },
  
  // -------------- 1-40 (Batch 1 & 2) --------------
  { artist: "Queen", song: "Bohemian Rhapsody", url: "https://www.azlyrics.com/lyrics/queen/bohemianrhapsody.html" },
  { artist: "Ed Sheeran", song: "Shape Of You", url: "https://www.azlyrics.com/lyrics/edsheeran/shapeofyou.html" },
  { artist: "Taylor Swift", song: "Shake It Off", url: "https://www.azlyrics.com/lyrics/taylorswift/shakeitoff.html" },
  { artist: "The Beatles", song: "Hey Jude", url: "https://www.azlyrics.com/lyrics/thebeatles/heyjude.html" },
  { artist: "Adele", song: "Someone Like You", url: "https://www.azlyrics.com/lyrics/adele/someonelikeyou.html" },
  { artist: "Eminem", song: "Lose Yourself", url: "https://www.azlyrics.com/lyrics/eminem/loseyourself.html" },
  { artist: "Billie Eilish", song: "Bad Guy", url: "https://www.azlyrics.com/lyrics/billieeilish/badguy.html" },
  { artist: "Michael Jackson", song: "Billie Jean", url: "https://www.azlyrics.com/lyrics/michaeljackson/billiejean.html" },
  { artist: "Dua Lipa", song: "Don't Start Now", url: "https://www.azlyrics.com/lyrics/dualipa/dontstartnow.html" },
  { artist: "Coldplay", song: "Viva La Vida", url: "https://www.azlyrics.com/lyrics/coldplay/vivalavida.html" },
  { artist: "Lady Gaga", song: "Bad Romance", url: "https://www.azlyrics.com/lyrics/ladygaga/badromance.html" },
  { artist: "Nirvana", song: "Smells Like Teen Spirit", url: "https://www.azlyrics.com/lyrics/nirvana/smellsliketeenspirit.html" },
  { artist: "Mark Ronson & Bruno Mars", song: "Uptown Funk", url: "https://www.azlyrics.com/lyrics/brunomars/uptownfunk.html" },
  { artist: "Rihanna", song: "Umbrella", url: "https://www.azlyrics.com/lyrics/rihanna/umbrella.html" },
  { artist: "Justin Bieber", song: "Sorry", url: "https://www.azlyrics.com/lyrics/justinbieber/sorry.html" },
  { artist: "Imagine Dragons", song: "Radioactive", url: "https://www.azlyrics.com/lyrics/imaginedragons/radioactive.html" },
  { artist: "Ariana Grande", song: "thank u, next", url: "https://www.azlyrics.com/lyrics/arianagrande/thankunext.html" },
  { artist: "The Weeknd", song: "Blinding Lights", url: "https://www.azlyrics.com/lyrics/theweeknd/blindinglights.html" },
  { artist: "Katy Perry", song: "Firework", url: "https://www.azlyrics.com/lyrics/katyperry/firework.html" },
  { artist: "Sam Smith", song: "Stay With Me", url: "https://www.azlyrics.com/lyrics/samsmith/staywithme.html" },
  { artist: "Linkin Park", song: "Numb", url: "https://www.azlyrics.com/lyrics/linkinpark/numb.html" },
  { artist: "Lil Nas X", song: "Old Town Road", url: "https://www.azlyrics.com/lyrics/lilnasx/oldtownroad.html" },
  { artist: "Maroon 5", song: "Sugar", url: "https://www.azlyrics.com/lyrics/maroon5/sugar.html" },
  { artist: "OneRepublic", song: "Counting Stars", url: "https://www.azlyrics.com/lyrics/onerepublic/countingstars.html" },
  { artist: "Sia", song: "Cheap Thrills", url: "https://www.azlyrics.com/lyrics/sia/cheapthrills.html" },
  { artist: "The Chainsmokers", song: "Closer", url: "https://www.azlyrics.com/lyrics/chainsmokers/closer.html" },
  { artist: "Luis Fonsi", song: "Despacito", url: "https://www.azlyrics.com/lyrics/luisfonsi/despacito.html" },
  { artist: "Imagine Dragons", song: "Believer", url: "https://www.azlyrics.com/lyrics/imaginedragons/believer.html" },
  { artist: "Bruno Mars", song: "Just The Way You Are", url: "https://www.azlyrics.com/lyrics/brunomars/justthewayyouare.html" },
  { artist: "Gotye", song: "Somebody That I Used To Know", url: "https://www.azlyrics.com/lyrics/gotye/somebodythatiusedtoknow.html" },
  { artist: "Avicii", song: "Wake Me Up", url: "https://www.azlyrics.com/lyrics/avicii/wakemeup.html" },
  { artist: "Passenger", song: "Let Her Go", url: "https://www.azlyrics.com/lyrics/passenger/lethergo.html" },
  { artist: "Shawn Mendes", song: "Stitches", url: "https://www.azlyrics.com/lyrics/shawnmendes/stitches.html" },
  { artist: "Daft Punk", song: "Get Lucky", url: "https://www.azlyrics.com/lyrics/daftpunk/getlucky.html" },
  { artist: "P!nk", song: "Just Give Me A Reason", url: "https://www.azlyrics.com/lyrics/pink/justgivemeareason.html" },
  { artist: "John Legend", song: "All of Me", url: "https://www.azlyrics.com/lyrics/johnlegend/allofme.html" },
  { artist: "Pharrell Williams", song: "Happy", url: "https://www.azlyrics.com/lyrics/pharrellwilliams/happy.html" },
  { artist: "Lorde", song: "Royals", url: "https://www.azlyrics.com/lyrics/lorde/royals.html" },
  { artist: "Hozier", song: "Take Me To Church", url: "https://www.azlyrics.com/lyrics/hozier/takemetochurch.html" },
  { artist: "Vance Joy", song: "Riptide", url: "https://www.azlyrics.com/lyrics/vancejoy/riptide.html" },

  // -------------- 41-107 ( -Batch 3 & 4) --------------
  { artist: "Doja Cat", song: "Say So", url: "https://www.azlyrics.com/lyrics/dojacat/sayso.html" },
  { artist: "Harry Styles", song: "Watermelon Sugar", url: "https://www.azlyrics.com/lyrics/harrystyles/watermelonsugar.html" },
  { artist: "Lil Wayne", song: "Lollipop", url: "https://www.azlyrics.com/lyrics/lilwayne/lollipop.html" },
  { artist: "Rihanna", song: "Diamonds", url: "https://www.azlyrics.com/lyrics/rihanna/diamonds.html" },
  { artist: "Avril Lavigne", song: "Complicated", url: "https://www.azlyrics.com/lyrics/avrillavigne/complicated.html" },
  { artist: "The Killers", song: "Mr. Brightside", url: "https://www.azlyrics.com/lyrics/killers/mrbrightside.html" },
  { artist: "Oasis", song: "Wonderwall", url: "https://www.azlyrics.com/lyrics/oasis/wonderwall.html" },
  { artist: "Britney Spears", song: "Baby One More Time", url: "https://www.azlyrics.com/lyrics/britneyspears/babyonemoretime.html" },
  { artist: "AC/DC", song: "Back In Black", url: "https://www.azlyrics.com/lyrics/acdc/backinblack.html" },
  { artist: "Guns N' Roses", song: "Sweet Child O' Mine", url: "https://www.azlyrics.com/lyrics/gunsnroses/sweetchildomine.html" },
  { artist: "Bruno Mars", song: "Grenade", url: "https://www.azlyrics.com/lyrics/brunomars/grenade.html" },
  { artist: "Bruno Mars", song: "Runaway Baby", url: "https://www.azlyrics.com/lyrics/brunomars/runawaybaby.html" },
  { artist: "Bruno Mars", song: "The Lazy Song", url: "https://www.azlyrics.com/lyrics/brunomars/thelazysong.html" },
  { artist: "Bruno Mars", song: "Talking to the Moon", url: "https://www.azlyrics.com/lyrics/brunomars/talkingtothemoon.html" },
  { artist: "Bruno Mars", song: "Marry You", url: "https://www.azlyrics.com/lyrics/brunomars/marryyou.html" },
  { artist: "Dua Lipa", song: "Physical", url: "https://www.azlyrics.com/lyrics/dualipa/physical.html" },
  { artist: "Dua Lipa", song: "Levitating", url: "https://www.azlyrics.com/lyrics/dualipa/levitating.html" },
  { artist: "Dua Lipa", song: "Break My Heart", url: "https://www.azlyrics.com/lyrics/dualipa/breakmyheart.html" },
  { artist: "Dua Lipa", song: "Hallucinate", url: "https://www.azlyrics.com/lyrics/dualipa/hallucinate.html" },
  { artist: "Ed Sheeran", song: "Castle On The Hill", url: "https://www.azlyrics.com/lyrics/edsheeran/castleonthehill.html" },
  { artist: "Ed Sheeran", song: "Galway Girl", url: "https://www.azlyrics.com/lyrics/edsheeran/galwaygirl.html" },
  { artist: "Ed Sheeran", song: "Perfect", url: "https://www.azlyrics.com/lyrics/edsheeran/perfect.html" },
  { artist: "Ed Sheeran", song: "Happier", url: "https://www.azlyrics.com/lyrics/edsheeran/happier.html" },
  { artist: "Ed Sheeran", song: "Dive", url: "https://www.azlyrics.com/lyrics/edsheeran/dive.html" },
  { artist: "Ed Sheeran", song: "New Man", url: "https://www.azlyrics.com/lyrics/edsheeran/newman.html" },
  { artist: "Ed Sheeran", song: "Supermarket Flowers", url: "https://www.azlyrics.com/lyrics/edsheeran/supermarketflowers.html" },
  { artist: "Adele", song: "Rolling In The Deep", url: "https://www.azlyrics.com/lyrics/adele/rollinginthedeep.html" },
  { artist: "Adele", song: "Set Fire To The Rain", url: "https://www.azlyrics.com/lyrics/adele/setfiretotherain.html" },
  { artist: "Adele", song: "Turning Tables", url: "https://www.azlyrics.com/lyrics/adele/turningtables.html" },
  { artist: "Michael Jackson", song: "Thriller", url: "https://www.azlyrics.com/lyrics/michaeljackson/thriller.html" },
  { artist: "Michael Jackson", song: "Beat It", url: "https://www.azlyrics.com/lyrics/michaeljackson/beatit.html" },
  { artist: "Michael Jackson", song: "Wanna Be Startin' Somethin'", url: "https://www.azlyrics.com/lyrics/michaeljackson/wannabestartinsomethin.html" },
  { artist: "Michael Jackson", song: "Human Nature", url: "https://www.azlyrics.com/lyrics/michaeljackson/humannature.html" },
  { artist: "Eminem", song: "The Real Slim Shady", url: "https://www.azlyrics.com/lyrics/eminem/therealslimshady.html" },
  { artist: "Eminem", song: "Stan", url: "https://www.azlyrics.com/lyrics/eminem/stan.html" },
  { artist: "Eminem", song: "Drug Ballad", url: "https://www.azlyrics.com/lyrics/eminem/drugballad.html" },
  { artist: "Eminem", song: "Bitch Please II", url: "https://www.azlyrics.com/lyrics/eminem/bitchpleaseii.html" },
  { artist: "Nirvana", song: "Come As You Are", url: "https://www.azlyrics.com/lyrics/nirvana/comeasyouare.html" },
  { artist: "Nirvana", song: "Lithium", url: "https://www.azlyrics.com/lyrics/nirvana/lithium.html" },
  { artist: "Nirvana", song: "In Bloom", url: "https://www.azlyrics.com/lyrics/nirvana/inbloom.html" },
  { artist: "Linkin Park", song: "In The End", url: "https://www.azlyrics.com/lyrics/linkinpark/intheend.html" },
  { artist: "Linkin Park", song: "Crawling", url: "https://www.azlyrics.com/lyrics/linkinpark/crawling.html" },
  { artist: "Linkin Park", song: "One Step Closer", url: "https://www.azlyrics.com/lyrics/linkinpark/onestepcloser.html" },
  { artist: "Coldplay", song: "Clocks", url: "https://www.azlyrics.com/lyrics/coldplay/clocks.html" },
  { artist: "Coldplay", song: "The Scientist", url: "https://www.azlyrics.com/lyrics/coldplay/thescientist.html" },
  { artist: "Coldplay", song: "In My Place", url: "https://www.azlyrics.com/lyrics/coldplay/inmyplace.html" },
  { artist: "Taylor Swift", song: "Blank Space", url: "https://www.azlyrics.com/lyrics/taylorswift/blankspace.html" },
  { artist: "Taylor Swift", song: "Style", url: "https://www.azlyrics.com/lyrics/taylorswift/style.html" },
  { artist: "Taylor Swift", song: "Bad Blood", url: "https://www.azlyrics.com/lyrics/taylorswift/badblood.html" },
  { artist: "Lady Gaga", song: "Poker Face", url: "https://www.azlyrics.com/lyrics/ladygaga/pokerface.html" },
  { artist: "Lady Gaga", song: "Just Dance", url: "https://www.azlyrics.com/lyrics/ladygaga/justdance.html" },
  { artist: "Lady Gaga", song: "Alejandro", url: "https://www.azlyrics.com/lyrics/ladygaga/alejandro.html" },
  { artist: "Sam Smith", song: "I'm Not The Only One", url: "https://www.azlyrics.com/lyrics/samsmith/imnottheonlyone.html" },
  { artist: "Sam Smith", song: "Lay Me Down", url: "https://www.azlyrics.com/lyrics/samsmith/laymedown.html" },
  { artist: "Katy Perry", song: "California Gurls", url: "https://www.azlyrics.com/lyrics/katyperry/californiagurls.html" },
  { artist: "Katy Perry", song: "Last Friday Night (T.G.I.F.)", url: "https://www.azlyrics.com/lyrics/katyperry/lastfridaynighttgif.html" },
  { artist: "Katy Perry", song: "The One That Got Away", url: "https://www.azlyrics.com/lyrics/katyperry/theonethatgotaway.html" },
  { artist: "Green Day", song: "American Idiot", url: "https://www.azlyrics.com/lyrics/greenday/americanidiot.html" },
  { artist: "Green Day", song: "Holiday", url: "https://www.azlyrics.com/lyrics/greenday/holiday.html" },
  { artist: "Green Day", song: "Wake Me Up When September Ends", url: "https://www.azlyrics.com/lyrics/greenday/wakemeupwhenseptemberends.html" },
  { artist: "The Beatles", song: "Lucy In The Sky With Diamonds", url: "https://www.azlyrics.com/lyrics/beatles/lucyintheskywithdiamonds.html" },
  { artist: "The Beatles", song: "A Day In The Life", url: "https://www.azlyrics.com/lyrics/beatles/adayinthelife.html" },
  { artist: "Queen", song: "We Will Rock You", url: "https://www.azlyrics.com/lyrics/queen/wewillrockyou.html" },
  { artist: "Queen", song: "Don't Stop Me Now", url: "https://www.azlyrics.com/lyrics/queen/dontstopmenow.html" },
  { artist: "The Rolling Stones", song: "Paint It Black", url: "https://www.azlyrics.com/lyrics/rollingstones/paintitblack.html" },
  { artist: "The Eagles", song: "Hotel California", url: "https://www.azlyrics.com/lyrics/eagles/hotelcalifornia.html" },
  { artist: "Elton John", song: "Tiny Dancer", url: "https://www.azlyrics.com/lyrics/eltonjohn/tinydancer.html" },
  { artist: "Madonna", song: "Like A Prayer", url: "https://www.azlyrics.com/lyrics/madonna/likeaprayer.html" },
  { artist: "Whitney Houston", song: "I Will Always Love You", url: "https://www.azlyrics.com/lyrics/whitneyhouston/iwillalwaysloveyou.html" },
  { artist: "David Bowie", song: "Heroes", url: "https://www.azlyrics.com/lyrics/davidbowie/heroes.html" },
  { artist: "Led Zeppelin", song: "Stairway To Heaven", url: "https://www.azlyrics.com/lyrics/ledzeppelin/stairwaytoheaven.html" },
  { artist: "Post Malone", song: "Circles", url: "https://www.azlyrics.com/lyrics/postmalone/circles.html" },
  { artist: "Travis Scott", song: "Sicko Mode", url: "https://www.azlyrics.com/lyrics/travisscott/sickomode.html" },
  { artist: "Drake", song: "God's Plan", url: "https://www.azlyrics.com/lyrics/drake/godsplan.html" },
  { artist: "BTS", song: "Dynamite", url: "https://www.azlyrics.com/lyrics/bts/dynamite.html" },
  { artist: "Doja Cat", song: "Kiss Me More", url: "https://www.azlyrics.com/lyrics/dojacat/kissmemore.html" },
  { artist: "The Weeknd", song: "Save Your Tears", url: "https://www.azlyrics.com/lyrics/theweeknd/saveyourtears.html" },
  { artist: "Dua Lipa", song: "New Rules", url: "https://www.azlyrics.com/lyrics/dualipa/newrules.html" },
  { artist: "Lil Nas X", song: "Montero (Call Me By Your Name)", url: "https://www.azlyrics.com/lyrics/lilnasx/monterocallmebyyourname.html" },
  { artist: "Glass Animals", song: "Heat Waves", url: "https://www.azlyrics.com/lyrics/glassanimals/heatwaves.html" },
  { artist: "Harry Styles", song: "As It Was", url: "https://www.azlyrics.com/lyrics/harrystyles/asitwas.html" },
  { artist: "Elton John", song: "Rocket Man", url: "https://www.azlyrics.com/lyrics/eltonjohn/rocketman.html" },
  { artist: "ABBA", song: "Dancing Queen", url: "https://www.azlyrics.com/lyrics/abba/dancingqueen.html" },
  { artist: "OutKast", song: "Hey Ya!", url: "https://www.azlyrics.com/lyrics/outkast/heyya.html" },
  { artist: "R.E.M.", song: "Losing My Religion", url: "https://www.azlyrics.com/lyrics/rem/losingmyreligion.html" },
  { artist: "Radiohead", song: "Creep", url: "https://www.azlyrics.com/lyrics/radiohead/creep.html" },
  { artist: "Britney Spears", song: "Toxic", url: "https://www.azlyrics.com/lyrics/britneyspears/toxic.html" },
  { artist: "Eurythmics", song: "Sweet Dreams (Are Made Of This)", url: "https://www.azlyrics.com/lyrics/eurythmics/sweetdreamsaremadeofthis.html" },
  { artist: "A-Ha", song: "Take On Me", url: "https://www.azlyrics.com/lyrics/aha/takeonme.html" },
  { artist: "The Police", song: "Every Breath You Take", url: "https://www.azlyrics.com/lyrics/police/everybreathyoutake.html" },
  { artist: "U2", song: "With Or Without You", url: "https://www.azlyrics.com/lyrics/u2/withorwithoutyou.html" },
  { artist: "Metallica", song: "Enter Sandman", url: "https://www.azlyrics.com/lyrics/metallica/entersandman.html" },
  { artist: "Red Hot Chili Peppers", song: "Californication", url: "https://www.azlyrics.com/lyrics/redhotchilipeppers/californication.html" },
  { artist: "Foo Fighters", song: "Everlong", url: "https://www.azlyrics.com/lyrics/foofighters/everlong.html" },
  { artist: "Paramore", song: "Misery Business", url: "https://www.azlyrics.com/lyrics/paramore/miserybusiness.html" },
  { artist: "Fall Out Boy", song: "Sugar, We're Goin Down", url: "https://www.azlyrics.com/lyrics/falloutboy/sugarweregoindown.html" },
  { artist: "My Chemical Romance", song: "Welcome To The Black Parade", url: "https://www.azlyrics.com/lyrics/mychemicalromance/welcometotheblackparade.html" },

  // -------------- 108-207 (Batch 5) --------------
  { artist: "Beyonce", song: "Formation", url: "https://www.azlyrics.com/lyrics/beyonce/formation.html" },
  { artist: "Beyonce", song: "Halo", url: "https://www.azlyrics.com/lyrics/beyonce/halo.html" },
  { artist: "Beyonce", song: "Single Ladies (Put A Ring On It)", url: "https://www.azlyrics.com/lyrics/beyonce/singleladiesputaringonit.html" },
  { artist: "Beyonce", song: "Crazy In Love", url: "https://www.azlyrics.com/lyrics/beyonce/crazyinlove.html" },
  { artist: "Beyonce", song: "Drunk In Love", url: "https://www.azlyrics.com/lyrics/beyonce/drunkinlove.html" },
  { artist: "Rihanna", song: "Work", url: "https://www.azlyrics.com/lyrics/rihanna/work.html" },
  { artist: "Rihanna", song: "We Found Love", url: "https://www.azlyrics.com/lyrics/rihanna/wefoundlove.html" },
  { artist: "Rihanna", song: "Don't Stop The Music", url: "https://www.azlyrics.com/lyrics/rihanna/dontstopthemusic.html" },
  { artist: "Rihanna", song: "Disturbia", url: "https://www.azlyrics.com/lyrics/rihanna/disturbia.html" },
  { artist: "Rihanna", song: "Take A Bow", url: "https://www.azlyrics.com/lyrics/rihanna/takeabow.html" },
  { artist: "Kendrick Lamar", song: "HUMBLE.", url: "https://www.azlyrics.com/lyrics/kendricklamar/humble.html" },
  { artist: "Kendrick Lamar", song: "DNA.", url: "https://www.azlyrics.com/lyrics/kendricklamar/dna.html" },
  { artist: "Kendrick Lamar", song: "Bitch, Don't Kill My Vibe", url: "https://www.azlyrics.com/lyrics/kendricklamar/bitchdontkillmyvibe.html" },
  { artist: "Kendrick Lamar", song: "Swimming Pools (Drank)", url: "https://www.azlyrics.com/lyrics/kendricklamar/swimmingpoolsdrank.html" },
  { artist: "Ariana Grande", song: "7 Rings", url: "https://www.azlyrics.com/lyrics/arianagrande/7rings.html" },
  { artist: "Ariana Grande", song: "God Is A Woman", url: "https://www.azlyrics.com/lyrics/arianagrande/godisawoman.html" },
  { artist: "Ariana Grande", song: "No Tears Left To Cry", url: "https://www.azlyrics.com/lyrics/arianagrande/notearslefttocry.html" },
  { artist: "Queen", song: "Love Of My Life", url: "https://www.azlyrics.com/lyrics/queen/loveofmylife.html" },
  { artist: "Queen", song: "You're My Best Friend", url: "https://www.azlyrics.com/lyrics/queen/yourmybestfriend.html" },
  { artist: "The Rolling Stones", song: "Satisfaction", url: "https://www.azlyrics.com/lyrics/rollingstones/satisfaction.html" },
  { artist: "The Rolling Stones", song: "Sympathy For The Devil", url: "https://www.azlyrics.com/lyrics/rollingstones/sympathyforthedevil.html" },
  { artist: "The Rolling Stones", song: "Gimme Shelter", url: "https://www.azlyrics.com/lyrics/rollingstones/gimmeshelter.html" },
  { artist: "Elton John", song: "Candle In The Wind", url: "https://www.azlyrics.com/lyrics/eltonjohn/candleinthewind.html" },
  { artist: "Elton John", song: "Bennie And The Jets", url: "https://www.azlyrics.com/lyrics/eltonjohn/bennieandthejets.html" },
  { artist: "The Police", song: "Roxanne", url: "https://www.azlyrics.com/lyrics/police/roxanne.html" },
  { artist: "The Police", song: "Message In A Bottle", url: "https://www.azlyrics.com/lyrics/police/messageinabottle.html" },
  { artist: "Bob Marley", song: "No Woman, No Cry", url: "https://www.azlyrics.com/lyrics/bobmarley/nowomannocry.html" },
  { artist: "Bob Marley", song: "Three Little Birds", url: "https://www.azlyrics.com/lyrics/bobmarley/threelittlebirds.html" },
  { artist: "Bob Marley", song: "One Love", url: "https://www.azlyrics.com/lyrics/bobmarley/onelove.html" },
  { artist: "Bob Dylan", song: "Like A Rolling Stone", url: "https://www.azlyrics.com/lyrics/bobdylan/likearollingstone.html" },
  { artist: "Bob Dylan", song: "Knockin' On Heaven's Door", url: "https://www.azlyrics.com/lyrics/bobdylan/knockinonheavensdoor.html" },
  { artist: "The Beach Boys", song: "Good Vibrations", url: "https://www.azlyrics.com/lyrics/beachboys/goodvibrations.html" },
  { artist: "The Beach Boys", song: "God Only Knows", url: "https://www.azlyrics.com/lyrics/beachboys/godonlyknows.html" },
  { artist: "Michael Jackson", song: "Smooth Criminal", url: "https://www.azlyrics.com/lyrics/michaeljackson/smoothcriminal.html" },
  { artist: "Michael Jackson", song: "Man In The Mirror", url: "https://www.azlyrics.com/lyrics/michaeljackson/maninthemirror.html" },
  { artist: "Guns N' Roses", song: "Paradise City", url: "https://www.azlyrics.com/lyrics/gunsnroses/paradisecity.html" },
  { artist: "Guns N' Roses", song: "Welcome To The Jungle", url: "https://www.azlyrics.com/lyrics/gunsnroses/welcometothejungle.html" },
  { artist: "Red Hot Chili Peppers", song: "Under The Bridge", url: "https://www.azlyrics.com/lyrics/redhotchilipeppers/underthebridge.html" },
  { artist: "Red Hot Chili Peppers", song: "By The Way", url: "https://www.azlyrics.com/lyrics/redhotchilipeppers/bytheway.html" },
  { artist: "Green Day", song: "Basket Case", url: "https://www.azlyrics.com/lyrics/greenday/basketcase.html" },
  { artist: "Green Day", song: "When I Come Around", url: "https://www.azlyrics.com/lyrics/greenday/whenicomearound.html" },
  { artist: "Lady Gaga", song: "Paparazzi", url: "https://www.azlyrics.com/lyrics/ladygaga/paparazzi.html" },
  { artist: "Lady Gaga", song: "Born This Way", url: "https://www.azlyrics.com/lyrics/ladygaga/bornthisway.html" },
  { artist: "Ed Sheeran", song: "Thinking Out Loud", url: "https://www.azlyrics.com/lyrics/edsheeran/thinkingoutloud.html" },
  { artist: "Ed Sheeran", song: "Photograph", url: "https://www.azlyrics.com/lyrics/edsheeran/photograph.html" },
  { artist: "Adele", song: "Hello", url: "https://www.azlyrics.com/lyrics/adele/hello.html" },
  { artist: "Adele", song: "Send My Love (To Your New Lover)", url: "https://www.azlyrics.com/lyrics/adele/sendmylovetoyournewlover.html" },
  { artist: "The Chainsmokers", song: "Paris", url: "https://www.azlyrics.com/lyrics/chainsmokers/paris.html" },
  { artist: "The Chainsmokers", song: "Something Just Like This", url: "https://www.azlyrics.com/lyrics/chainsmokers/somethingjustlikethis.html" },
  { artist: "Post Malone", song: "Sunflower", url: "https://www.azlyrics.com/lyrics/postmalone/sunflower.html" },
  { artist: "Post Malone", song: "Rockstar", url: "https://www.azlyrics.com/lyrics/postmalone/rockstar.html" },
  { artist: "Post Malone", song: "Better Now", url: "https://www.azlyrics.com/lyrics/postmalone/betternow.html" },
  { artist: "Maroon 5", song: "Moves Like Jagger", url: "https://www.azlyrics.com/lyrics/maroon5/moveslikejagger.html" },
  { artist: "Maroon 5", song: "Memories", url: "https://www.azlyrics.com/lyrics/maroon5/memories.html" },
  { artist: "The Weeknd", song: "Starboy", url: "https://www.azlyrics.com/lyrics/theweeknd/starboy.html" },
  { artist: "The Weeknd", song: "The Hills", url: "https://www.azlyrics.com/lyrics/theweeknd/thehills.html" },
  { artist: "The Weeknd", song: "Can't Feel My Face", url: "https://www.azlyrics.com/lyrics/theweeknd/cantfeelmyface.html" },
  { artist: "Justin Bieber", song: "Love Yourself", url: "https://www.azlyrics.com/lyrics/justinbieber/loveyourself.html" },
  { artist: "Justin Bieber", song: "What Do You Mean?", url: "https://www.azlyrics.com/lyrics/justinbieber/whatdoyoumean.html" },
  { artist: "Taylor Swift", song: "Love Story", url: "https://www.azlyrics.com/lyrics/taylorswift/lovestory.html" },
  { artist: "Taylor Swift", song: "You Belong With Me", url: "https://www.azlyrics.com/lyrics/taylorswift/youbelongwithme.html" },
  { artist: "Taylor Swift", song: "We Are Never Ever Getting Back Together", url: "https://www.azlyrics.com/lyrics/taylorswift/weareneverevergettingbacktogether.html" },
  { artist: "Coldplay", song: "Fix You", url: "https://www.azlyrics.com/lyrics/coldplay/fixyou.html" },
  { artist: "Coldplay", song: "Yellow", url: "https://www.azlyrics.com/lyrics/coldplay/yellow.html" },
  { artist: "Imagine Dragons", song: "Demons", url: "https://www.azlyrics.com/lyrics/imaginedragons/demons.html" },
  { artist: "Imagine Dragons", song: "It's Time", url: "https://www.azlyrics.com/lyrics/imaginedragons/itstime.html" },
  { artist: "Daft Punk", song: "One More Time", url: "https://www.azlyrics.com/lyrics/daftpunk/onemoretime.html" },
  { artist: "Daft Punk", song: "Harder, Better, Faster, Stronger", url: "https://www.azlyrics.com/lyrics/daftpunk/harderbetterfasterstronger.html" },
  { artist: "Eminem", song: "Not Afraid", url: "https://www.azlyrics.com/lyrics/eminem/notafraid.html" },
  { artist: "Eminem", song: "Love The Way You Lie", url: "https://www.azlyrics.com/lyrics/eminem/lovethewayyoulie.html" },
  { artist: "The Beatles", song: "Yesterday", url: "https://www.azlyrics.com/lyrics/beatles/yesterday.html" },
  { artist: "The Beatles", song: "Let It Be", url: "https://www.azlyrics.com/lyrics/beatles/letitbe.html" },
  { artist: "The Beatles", song: "Come Together", url: "https://www.azlyrics.com/lyrics/beatles/cometogether.html" },
  { artist: "The Beatles", song: "Twist And Shout", url: "https://www.azlyrics.com/lyrics/beatles/twistandshout.html" },
  { artist: "David Bowie", song: "Space Oddity", url: "https://www.azlyrics.com/lyrics/davidbowie/spaceoddity.html" },
  { artist: "David Bowie", song: "Ziggy Stardust", url: "https://www.azlyrics.com/lyrics/davidbowie/ziggystardust.html" },
  { artist: "Nirvana", song: "Heart-Shaped Box", url: "https://www.azlyrics.com/lyrics/nirvana/heartshapedbox.html" },
  { artist: "Nirvana", song: "All Apologies", url: "https://www.azlyrics.com/lyrics/nirvana/allapologies.html" },
  { artist: "Amy Winehouse", song: "Rehab", url: "https://www.azlyrics.com/lyrics/amywinehouse/rehab.html" },
  { artist: "Amy Winehouse", song: "Back To Black", url: "https://www.azlyrics.com/lyrics/amywinehouse/backtoblack.html" },
  { artist: "Bruno Mars", song: "24K Magic", url: "https://www.azlyrics.com/lyrics/brunomars/24kmagic.html" },
  { artist: "Bruno Mars", song: "Finesse", url: "https://www.azlyrics.com/lyrics/brunomars/finesse.html" },
  { artist: "Sia", song: "Chandelier", url: "https://www.azlyrics.com/lyrics/sia/chandelier.html" },
  { artist: "Sia", song: "Elastic Heart", url: "https://www.azlyrics.com/lyrics/sia/elasticheart.html" },
  { artist: "Pink", song: "Raise Your Glass", url: "https://www.azlyrics.com/lyrics/pink/raiseyourglass.html" },
  { artist: "Pink", song: "Get The Party Started", url: "https://www.azlyrics.com/lyrics/pink/getthepartystarted.html" },
  { artist: "OneRepublic", song: "Apologize", url: "https://www.azlyrics.com/lyrics/onerepublic/apologize.html" },
  { artist: "OneRepublic", song: "Secrets", url: "https://www.azlyrics.com/lyrics/onerepublic/secrets.html" },
  { artist: "Foo Fighters", song: "The Pretender", url: "https://www.azlyrics.com/lyrics/foofighters/thepretender.html" },
  { artist: "Foo Fighters", song: "Learn To Fly", url: "https://www.azlyrics.com/lyrics/foofighters/learntofly.html" },
  { artist: "Oasis", song: "Don't Look Back In Anger", url: "https://www.azlyrics.com/lyrics/oasis/dontlookbackinanger.html" },
  { artist: "Oasis", song: "Champagne Supernova", url: "https://www.azlyrics.com/lyrics/oasis/champagnesupernova.html" },
  { artist: "The Killers", song: "When You Were Young", url: "https://www.azlyrics.com/lyrics/killers/whenyouwereyoung.html" },
  { artist: "The Killers", song: "All These Things That I've Done", url: "https://www.azlyrics.com/lyrics/killers/allthesethingsthativedone.html" },
  { artist: "Alanis Morissette", song: "Ironic", url: "https://www.azlyrics.com/lyrics/alanismorissette/ironic.html" },
  { artist: "Alanis Morissette", song: "You Oughta Know", url: "https://www.azlyrics.com/lyrics/alanismorissette/yououghtaknow.html" },
  { artist: "Spice Girls", song: "Wannabe", url: "https://www.azlyrics.com/lyrics/spicegirls/wannabe.html" },
  { artist: "Backstreet Boys", song: "I Want It That Way", url: "https://www.azlyrics.com/lyrics/backstreetboys/iwantitthatway.html" },
  { artist: "NSYNC", song: "Bye Bye Bye", url: "https://www.azlyrics.com/lyrics/nsync/byebyebye.html" },
  { artist: "Christina Aguilera", song: "Genie In A Bottle", url: "https://www.azlyrics.com/lyrics/christinaaguilera/genieinabottle.html" },
  { artist: "Ricky Martin", song: "Livin' La Vida Loca", url: "https://www.azlyrics.com/lyrics/rickymartin/livinlavidaloca.html" },
  { artist: "Lou Bega", song: "Mambo No. 5 (A Little Bit Of...)", url: "https://www.azlyrics.com/lyrics/loubega/mambono5alittlebitof.html" },
  { artist: "Britney Spears", song: "Oops!... I Did It Again", url: "https://www.azlyrics.com/lyrics/britneyspears/oopsididitagain.html" },
  { artist: "Britney Spears", song: "Stronger", url: "https://www.azlyrics.com/lyrics/britneyspears/stronger.html" },
  { artist: "Destinys Child", song: "Survivor", url: "https://www.azlyrics.com/lyrics/destinyschild/survivor.html" },
  { artist: "Destinys Child", song: "Independent Women Part I", url: "https://www.azlyrics.com/lyrics/destinyschild/independentwomenparti.html" },
  { artist: "Nelly", song: "Hot In Herre", url: "https://www.azlyrics.com/lyrics/nelly/hotinherre.html" },
  { artist: "Usher", song: "Yeah!", url: "https://www.azlyrics.com/lyrics/usher/yeah.html" },
  { artist: "Gwen Stefani", song: "Hollaback Girl", url: "https://www.azlyrics.com/lyrics/gwenstefani/hollabackgirl.html" },
  { artist: "James Blunt", song: "You're Beautiful", url: "https://www.azlyrics.com/lyrics/jamesblunt/yourebeautiful.html" },
  { artist: "The Black Eyed Peas", song: "I Gotta Feeling", url: "https://www.azlyrics.com/lyrics/blackeyedpeas/igottafeeling.html" },
  { artist: "Kings Of Leon", song: "Sex On Fire", url: "https://www.azlyrics.com/lyrics/kingsofleon/sexonfire.html" },
  { artist: "Lorde", song: "Team", url: "https://www.azlyrics.com/lyrics/lorde/team.html" },
  { artist: "Hozier", song: "Someone New", url: "https://www.azlyrics.com/lyrics/hozier/someonenew.html" },

  // -------------- 208-307 (Batch 6) --------------
  { artist: "Led Zeppelin", song: "Black Dog", url: "https://www.azlyrics.com/lyrics/ledzeppelin/blackdog.html" },
  { artist: "Led Zeppelin", song: "Rock And Roll", url: "https://www.azlyrics.com/lyrics/ledzeppelin/rockandroll.html" },
  { artist: "Led Zeppelin", song: "Misty Mountain Hop", url: "https://www.azlyrics.com/lyrics/ledzeppelin/mistymountainhop.html" },
  { artist: "Led Zeppelin", song: "The Battle Of Evermore", url: "https://www.azlyrics.com/lyrics/ledzeppelin/thebattleofevermore.html" },
  { artist: "Pink Floyd", song: "Money", url: "https://www.azlyrics.com/lyrics/pinkfloyd/money.html" },
  { artist: "Pink Floyd", song: "Us And Them", url: "https://www.azlyrics.com/lyrics/pinkfloyd/usandthem.html" },
  { artist: "Pink Floyd", song: "Comfortably Numb", url: "https://www.azlyrics.com/lyrics/pinkfloyd/comfortablynumb.html" },
  { artist: "Pink Floyd", song: "Another Brick In The Wall (Part 2)", url: "https://www.azlyrics.com/lyrics/pinkfloyd/anotherbrickinthewallpart2.html" },
  { artist: "Fleetwood Mac", song: "Dreams", url: "https://www.azlyrics.com/lyrics/fleetwoodmac/dreams.html" },
  { artist: "Fleetwood Mac", song: "Go Your Own Way", url: "https://www.azlyrics.com/lyrics/fleetwoodmac/goyourownway.html" },
  { artist: "Fleetwood Mac", song: "Rhiannon", url: "https://www.azlyrics.com/lyrics/fleetwoodmac/rhiannon.html" },
  { artist: "Dire Straits", song: "Sultans Of Swing", url: "https://www.azlyrics.com/lyrics/direstraits/sultansofswing.html" },
  { artist: "Dire Straits", song: "Brothers In Arms", url: "https://www.azlyrics.com/lyrics/direstraits/brothersinarms.html" },
  { artist: "George Michael", song: "Careless Whisper", url: "https://www.azlyrics.com/lyrics/georgemichael/carelesswhisper.html" },
  { artist: "Wham!", song: "Last Christmas", url: "https://www.azlyrics.com/lyrics/wham/lastchristmas.html" },
  { artist: "Wham!", song: "Wake Me Up Before You Go-Go", url: "https://www.azlyrics.com/lyrics/wham/wakemeupbeforeyougogo.html" },
  { artist: "Prince", song: "Purple Rain", url: "https://www.azlyrics.com/lyrics/prince/purplerain.html" },
  { artist: "Prince", song: "When Doves Cry", url: "https://www.azlyrics.com/lyrics/prince/whendovescry.html" },
  { artist: "Whitney Houston", song: "I Wanna Dance With Somebody (Who Loves Me)", url: "https://www.azlyrics.com/lyrics/whitneyhouston/iwannadancewithsomebodywholovesme.html" },
  { artist: "Madonna", song: "Vogue", url: "https://www.azlyrics.com/lyrics/madonna/vogue.html" },
  { artist: "Madonna", song: "Material Girl", url: "https://www.azlyrics.com/lyrics/madonna/materialgirl.html" },
  { artist: "Bon Jovi", song: "Livin' On A Prayer", url: "https://www.azlyrics.com/lyrics/bonjovi/livinonaprayer.html" },
  { artist: "Bon Jovi", song: "It's My Life", url: "https://www.azlyrics.com/lyrics/bonjovi/itsmylife.html" },
  { artist: "Bruce Springsteen", song: "Born To Run", url: "https://www.azlyrics.com/lyrics/brucespringsteen/borntorun.html" },
  { artist: "Bruce Springsteen", song: "Dancing In The Dark", url: "https://www.azlyrics.com/lyrics/brucespringsteen/dancinginthedark.html" },
  { artist: "The Cure", song: "Just Like Heaven", url: "https://www.azlyrics.com/lyrics/cure/justlikeheaven.html" },
  { artist: "The Smiths", song: "There Is A Light That Never Goes Out", url: "https://www.azlyrics.com/lyrics/smiths/thereisalightthatnevergoesout.html" },
  { artist: "The Cranberries", song: "Zombie", url: "https://www.azlyrics.com/lyrics/cranberries/zombie.html" },
  { artist: "Soundgarden", song: "Black Hole Sun", url: "https://www.azlyrics.com/lyrics/soundgarden/blackholesun.html" },
  { artist: "Pearl Jam", song: "Alive", url: "https://www.azlyrics.com/lyrics/pearljam/alive.html" },
  { artist: "The Verve", song: "Bitter Sweet Symphony", url: "https://www.azlyrics.com/lyrics/theverve/bittersweetsymphony.html" },
  { artist: "Oasis", song: "Supersonic", url: "https://www.azlyrics.com/lyrics/oasis/supersonic.html" },
  { artist: "Travis Scott", song: "Goosebumps", url: "https://www.azlyrics.com/lyrics/travisscott/goosebumps.html" },
  { artist: "Travis Scott", song: "Highest In The Room", url: "https://www.azlyrics.com/lyrics/travisscott/highestintheroom.html" },
  { artist: "Drake", song: "Hotline Bling", url: "https://www.azlyrics.com/lyrics/drake/hotlinebling.html" },
  { artist: "Drake", song: "In My Feelings", url: "https://www.azlyrics.com/lyrics/drake/inmyfeelings.html" },
  { artist: "Drake", song: "One Dance", url: "https://www.azlyrics.com/lyrics/drake/onedance.html" },
  { artist: "Lil Wayne", song: "A Milli", url: "https://www.azlyrics.com/lyrics/lilwayne/amilli.html" },
  { artist: "Jay-Z", song: "99 Problems", url: "https://www.azlyrics.com/lyrics/jayz/99problems.html" },
  { artist: "Jay-Z", song: "Empire State Of Mind", url: "https://www.azlyrics.com/lyrics/jayz/empirestateofmind.html" },
  { artist: "Kanye West", song: "Stronger", url: "https://www.azlyrics.com/lyrics/kanyewest/stronger.html" },
  { artist: "Kanye West", song: "Gold Digger", url: "https://www.azlyrics.com/lyrics/kanyewest/golddigger.html" },
  { artist: "Taylor Swift", song: "Cardigan", url: "https://www.azlyrics.com/lyrics/taylorswift/cardigan.html" },
  { artist: "Taylor Swift", song: "Willow", url: "https://www.azlyrics.com/lyrics/taylorswift/willow.html" },
  { artist: "Olivia Rodrigo", song: "Drivers License", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/driverslicense.html" },
  { artist: "Olivia Rodrigo", song: "Good 4 U", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/good4u.html" },
  { artist: "Doja Cat", song: "Need To Know", url: "https://www.azlyrics.com/lyrics/dojacat/needtoknow.html" },
  { artist: "Doja Cat", song: "Woman", url: "https://www.azlyrics.com/lyrics/dojacat/woman.html" },
  { artist: "Harry Styles", song: "Adore You", url: "https://www.azlyrics.com/lyrics/harrystyles/adoreyou.html" },
  { artist: "Harry Styles", song: "Falling", url: "https://www.azlyrics.com/lyrics/harrystyles/falling.html" },
  { artist: "The Weeknd", song: "I Feel It Coming", url: "https://www.azlyrics.com/lyrics/theweeknd/ifeelitcoming.html" },
  { artist: "Billie Eilish", song: "Ocean Eyes", url: "https://www.azlyrics.com/lyrics/billieeilish/oceaneyes.html" },
  { artist: "Billie Eilish", song: "Happier Than Ever", url: "https://www.azlyrics.com/lyrics/billieeilish/happierthanever.html" },
  { artist: "Lil Nas X", song: "Industry Baby", url: "https://www.azlyrics.com/lyrics/lilnasx/industrybaby.html" },
  { artist: "Megan Thee Stallion", song: "Savage", url: "https://www.azlyrics.com/lyrics/megantheestallion/savage.html" },
  { artist: "Cardi B", song: "WAP", url: "https://www.azlyrics.com/lyrics/cardib/wap.html" },
  { artist: "Lizzo", song: "Truth Hurts", url: "https://www.azlyrics.com/lyrics/lizzo/truthhurts.html" },
  { artist: "Halsey", song: "Without Me", url: "https://www.azlyrics.com/lyrics/halsey/withoutme.html" },
  { artist: "Shawn Mendes", song: "Señorita", url: "https://www.azlyrics.com/lyrics/shawnmendes/senorita.html" },
  { artist: "Zayn", song: "I Don't Wanna Live Forever", url: "https://www.azlyrics.com/lyrics/zayn/idontwannaliveforever.html" },
  { artist: "Justin Timberlake", song: "Cry Me A River", url: "https://www.azlyrics.com/lyrics/justintimberlake/crymeariver.html" },
  { artist: "Justin Timberlake", song: "SexyBack", url: "https://www.azlyrics.com/lyrics/justintimberlake/sexyback.html" },
  { artist: "Christina Aguilera", song: "Dirrty", url: "https://www.azlyrics.com/lyrics/christinaaguilera/dirrty.html" },
  { artist: "Avril Lavigne", song: "Sk8er Boi", url: "https://www.azlyrics.com/lyrics/avrillavigne/sk8erboi.html" },
  { artist: "Avril Lavigne", song: "Girlfriend", url: "https://www.azlyrics.com/lyrics/avrillavigne/girlfriend.html" },
  { artist: "Muse", song: "Starlight", url: "https://www.azlyrics.com/lyrics/muse/starlight.html" },
  { artist: "Muse", song: "Time Is Running Out", url: "https://www.azlyrics.com/lyrics/muse/timeisrunningout.html" },
  { artist: "Arctic Monkeys", song: "Do I Wanna Know?", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/doiwannaknow.html" },
  { artist: "Arctic Monkeys", song: "505", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/505.html" },
  { artist: "Gorillaz", song: "Feel Good Inc.", url: "https://www.azlyrics.com/lyrics/gorillaz/feelgoodinc.html" },
  { artist: "Gorillaz", song: "Clint Eastwood", url: "https://www.azlyrics.com/lyrics/gorillaz/clinteastwood.html" },
  { artist: "Jamiroquai", song: "Virtual Insanity", url: "https://www.azlyrics.com/lyrics/jamiroquai/virtualinsanity.html" },
  { artist: "The Fugees", song: "Killing Me Softly", url: "https://www.azlyrics.com/lyrics/fugees/killingmesoftly.html" },
  { artist: "Sublime", song: "Santeria", url: "https://www.azlyrics.com/lyrics/sublime/santeria.html" },
  { artist: "Smash Mouth", song: "All Star", url: "https://www.azlyrics.com/lyrics/smashmouth/allstar.html" },
  { artist: "Goo Goo Dolls", song: "Iris", url: "https://www.azlyrics.com/lyrics/googoodolls/iris.html" },
  { artist: "Third Eye Blind", song: "Jumper", url: "https://www.azlyrics.com/lyrics/thirdeyeblind/jumper.html" },
  { artist: "Radiohead", song: "Karma Police", url: "https://www.azlyrics.com/lyrics/radiohead/karmapolice.html" },
  { artist: "Jeff Buckley", song: "Hallelujah", url: "https://www.azlyrics.com/lyrics/jeffbuckley/hallelujah.html" },
  { artist: "Leonard Cohen", song: "Hallelujah", url: "https://www.azlyrics.com/lyrics/leonardcohen/hallelujah.html" },
  { artist: "Nat King Cole", song: "Unforgettable", url: "https://www.azlyrics.com/lyrics/natkingcole/unforgettable.html" },
  { artist: "Frank Sinatra", song: "My Way", url: "https://www.azlyrics.com/lyrics/franksinatra/myway.html" },
  { artist: "Frank Sinatra", song: "New York, New York", url: "https://www.azlyrics.com/lyrics/franksinatra/newyorknewyork.html" },
  { artist: "Louis Armstrong", song: "What A Wonderful World", url: "https://www.azlyrics.com/lyrics/louisarmstrong/whatawonderfulworld.html" },
  { artist: "Ray Charles", song: "Georgia On My Mind", url: "https://www.azlyrics.com/lyrics/raycharles/georgiaonmymind.html" },
  { artist: "Etta James", song: "At Last", url: "https://www.azlyrics.com/lyrics/ettajames/atlast.html" },
  { artist: "Aretha Franklin", song: "Respect", url: "https://www.azlyrics.com/lyrics/arethafranklin/respect.html" },
  { artist: "Marvin Gaye", song: "What's Going On", url: "https://www.azlyrics.com/lyrics/marvingaye/whatsgoingon.html" },
  { artist: "The Temptations", song: "My Girl", url: "https://www.azlyrics.com/lyrics/temptations/mygirl.html" },
  { artist: "Stevie Wonder", song: "Superstition", url: "https://www.azlyrics.com/lyrics/steviewonder/superstition.html" },
  { artist: "Earth, Wind & Fire", song: "September", url: "https://www.azlyrics.com/lyrics/earthwindfire/september.html" },
  { artist: "Bee Gees", song: "Stayin' Alive", url: "https://www.azlyrics.com/lyrics/beegees/stayinalive.html" },
  { artist: "Gloria Gaynor", song: "I Will Survive", url: "https://www.azlyrics.com/lyrics/gloriagaynor/iwillsurvive.html" },

  // -------------- 308-407 (Batch 7) --------------
  { artist: "Michael Jackson", song: "The Way You Make Me Feel", url: "https://www.azlyrics.com/lyrics/michaeljackson/thewayyoumakemefeel.html" },
  { artist: "Michael Jackson", song: "Black Or White", url: "https://www.azlyrics.com/lyrics/michaeljackson/blackorwhite.html" },
  { artist: "Prince", song: "Kiss", url: "https://www.azlyrics.com/lyrics/prince/kiss.html" },
  { artist: "Prince", song: "Raspberry Beret", url: "https://www.azlyrics.com/lyrics/prince/raspberryberet.html" },
  { artist: "Madonna", song: "Like A Virgin", url: "https://www.azlyrics.com/lyrics/madonna/likeavirgin.html" },
  { artist: "Madonna", song: "Hung Up", url: "https://www.azlyrics.com/lyrics/madonna/hungup.html" },
  { artist: "U2", song: "Where The Streets Have No Name", url: "https://www.azlyrics.com/lyrics/u2/wherethestreetshavenoname.html" },
  { artist: "U2", song: "Sunday Bloody Sunday", url: "https://www.azlyrics.com/lyrics/u2/sundaybloodysunday.html" },
  { artist: "U2", song: "One", url: "https://www.azlyrics.com/lyrics/u2/one.html" },
  { artist: "REM", song: "Everybody Hurts", url: "https://www.azlyrics.com/lyrics/rem/everybodyhurts.html" },
  { artist: "REM", song: "Man On The Moon", url: "https://www.azlyrics.com/lyrics/rem/manonthemoon.html" },
  { artist: "The Smiths", song: "Heaven Knows I'm Miserable Now", url: "https://www.azlyrics.com/lyrics/smiths/heavenknowsimmiserablenow.html" },
  { artist: "Depeche Mode", song: "Enjoy The Silence", url: "https://www.azlyrics.com/lyrics/depechemode/enjoythesilence.html" },
  { artist: "Depeche Mode", song: "Personal Jesus", url: "https://www.azlyrics.com/lyrics/depechemode/personaljesus.html" },
  { artist: "The Cure", song: "Close To Me", url: "https://www.azlyrics.com/lyrics/cure/closetome.html" },
  { artist: "New Order", song: "Blue Monday", url: "https://www.azlyrics.com/lyrics/neworder/bluemonday.html" },
  { artist: "The Clash", song: "London Calling", url: "https://www.azlyrics.com/lyrics/clash/londoncalling.html" },
  { artist: "The Clash", song: "Should I Stay Or Should I Go", url: "https://www.azlyrics.com/lyrics/clash/shouldistayorshouldigo.html" },
  { artist: "The Velvet Underground", song: "Sweet Jane", url: "https://www.azlyrics.com/lyrics/velvetunderground/sweetjane.html" },
  { artist: "The Doors", song: "Light My Fire", url: "https://www.azlyrics.com/lyrics/doors/lightmyfire.html" },
  { artist: "The Doors", song: "Riders On The Storm", url: "https://www.azlyrics.com/lyrics/doors/ridersonthestorm.html" },
  { artist: "Jimi Hendrix", song: "Purple Haze", url: "https://www.azlyrics.com/lyrics/jimihendrix/purplehaze.html" },
  { artist: "Jimi Hendrix", song: "All Along The Watchtower", url: "https://www.azlyrics.com/lyrics/jimihendrix/allalongthewatchtower.html" },
  { artist: "Janis Joplin", song: "Me And Bobby McGee", url: "https://www.azlyrics.com/lyrics/janisjoplin/meandbobbymcgee.html" },
  { artist: "The Who", song: "Baba O'Riley", url: "https://www.azlyrics.com/lyrics/thewho/babaoriley.html" },
  { artist: "The Kinks", song: "Lola", url: "https://www.azlyrics.com/lyrics/kinks/lola.html" },
  { artist: "The Monkees", song: "I'm A Believer", url: "https://www.azlyrics.com/lyrics/monkees/imabeliever.html" },
  { artist: "Dusty Springfield", song: "Son Of A Preacher Man", url: "https://www.azlyrics.com/lyrics/dustyspringfield/sonofapreacherman.html" },
  { artist: "Aretha Franklin", song: "Natural Woman", url: "https://www.azlyrics.com/lyrics/arethafranklin/naturalwoman.html" },
  { artist: "Otis Redding", song: "(Sittin' On) The Dock Of The Bay", url: "https://www.azlyrics.com/lyrics/otisredding/sittinonthedockofthebay.html" },
  { artist: "Sam Cooke", song: "A Change Is Gonna Come", url: "https://www.azlyrics.com/lyrics/samcooke/achangeisgonnacome.html" },
  { artist: "The Supremes", song: "You Can't Hurry Love", url: "https://www.azlyrics.com/lyrics/supremes/youcanthurrylove.html" },
  { artist: "Marvin Gaye", song: "Sexual Healing", url: "https://www.azlyrics.com/lyrics/marvingaye/sexualhealing.html" },
  { artist: "Tina Turner", song: "What's Love Got To Do With It", url: "https://www.azlyrics.com/lyrics/tinaturner/whatslovegottodowithit.html" },
  { artist: "Amy Winehouse", song: "Valerie", url: "https://www.azlyrics.com/lyrics/amywinehouse/valerie.html" },
  { artist: "Adele", song: "Skyfall", url: "https://www.azlyrics.com/lyrics/adele/skyfall.html" },
  { artist: "Sam Smith", song: "Writing's On The Wall", url: "https://www.azlyrics.com/lyrics/samsmith/writingsonthewall.html" },
  { artist: "Sia", song: "The Greatest", url: "https://www.azlyrics.com/lyrics/sia/thegreatest.html" },
  { artist: "Billie Eilish", song: "Therefore I Am", url: "https://www.azlyrics.com/lyrics/billieeilish/thereforeiam.html" },
  { artist: "Lil Nas X", song: "That's What I Want", url: "https://www.azlyrics.com/lyrics/lilnasx/thatswhatiwant.html" },
  { artist: "Doja Cat", song: "Streets", url: "https://www.azlyrics.com/lyrics/dojacat/streets.html" },
  { artist: "Megan Thee Stallion", song: "Body", url: "https://www.azlyrics.com/lyrics/megantheestallion/body.html" },
  { artist: "Cardi B", song: "Bodak Yellow", url: "https://www.azlyrics.com/lyrics/cardib/bodakyellow.html" },
  { artist: "Kendrick Lamar", song: "Money Trees", url: "https://www.azlyrics.com/lyrics/kendricklamar/moneytrees.html" },
  { artist: "Travis Scott", song: "Antidote", url: "https://www.azlyrics.com/lyrics/travisscott/antidote.html" },
  { artist: "Drake", song: "Take Care", url: "https://www.azlyrics.com/lyrics/drake/takecare.html" },
  { artist: "Drake", song: "Started From The Bottom", url: "https://www.azlyrics.com/lyrics/drake/startedfromthebottom.html" },
  { artist: "Post Malone", song: "White Iverson", url: "https://www.azlyrics.com/lyrics/postmalone/whiteiverson.html" },
  { artist: "Ed Sheeran", song: "The A Team", url: "https://www.azlyrics.com/lyrics/edsheeran/theateam.html" },
  { artist: "Ed Sheeran", song: "Lego House", url: "https://www.azlyrics.com/lyrics/edsheeran/legohouse.html" },
  { artist: "Avicii", song: "Levels", url: "https://www.azlyrics.com/lyrics/avicii/levels.html" },
  { artist: "Avicii", song: "Hey Brother", url: "https://www.azlyrics.com/lyrics/avicii/heybrother.html" },
  { artist: "The Chainsmokers", song: "Don't Let Me Down", url: "https://www.azlyrics.com/lyrics/chainsmokers/dontletmedown.html" },
  { artist: "Marshmello", song: "Happier", url: "https://www.azlyrics.com/lyrics/marshmello/happier.html" },
  { artist: "Alan Walker", song: "Faded", url: "https://www.azlyrics.com/lyrics/alanwalker/faded.html" },
  { artist: "Kygo", song: "Firestone", url: "https://www.azlyrics.com/lyrics/kygo/firestone.html" },
  { artist: "Jonas Brothers", song: "Sucker", url: "https://www.azlyrics.com/lyrics/jonasbrothers/sucker.html" },
  { artist: "5 Seconds Of Summer", song: "Youngblood", url: "https://www.azlyrics.com/lyrics/5secondsofsummer/youngblood.html" },
  { artist: "One Direction", song: "What Makes You Beautiful", url: "https://www.azlyrics.com/lyrics/onedirection/whatmakesyoubeautiful.html" },
  { artist: "One Direction", song: "Story Of My Life", url: "https://www.azlyrics.com/lyrics/onedirection/storyofmylife.html" },
  { artist: "Demi Lovato", song: "Skyscraper", url: "https://www.azlyrics.com/lyrics/demilovato/skyscraper.html" },
  { artist: "Selena Gomez", song: "Come & Get It", url: "https://www.azlyrics.com/lyrics/selenagomez/comegetit.html" },
  { artist: "Miley Cyrus", song: "Wrecking Ball", url: "https://www.azlyrics.com/lyrics/mileycyrus/wreckingball.html" },
  { artist: "Miley Cyrus", song: "Party In The U.S.A.", url: "https://www.azlyrics.com/lyrics/mileycyrus/partyintheusa.html" },
  { artist: "Bruno Mars", song: "When I Was Your Man", url: "https://www.azlyrics.com/lyrics/brunomars/wheniwasyourman.html" },
  { artist: "Bruno Mars", song: "Locked Out Of Heaven", url: "https://www.azlyrics.com/lyrics/brunomars/lockedoutofheaven.html" },
  { artist: "Adele", song: "Water Under The Bridge", url: "https://www.azlyrics.com/lyrics/adele/waterunderthebridge.html" },
  { artist: "John Legend", song: "Ordinary People", url: "https://www.azlyrics.com/lyrics/johnlegend/ordinarypeople.html" },
  { artist: "Sam Smith", song: "Too Good At Goodbyes", url: "https://www.azlyrics.com/lyrics/samsmith/toogoodatgoodbyes.html" },
  { artist: "Coldplay", song: "A Sky Full Of Stars", url: "https://www.azlyrics.com/lyrics/coldplay/askyfullofstars.html" },
  { artist: "Imagine Dragons", song: "Thunder", url: "https://www.azlyrics.com/lyrics/imaginedragons/thunder.html" },
  { artist: "The Killers", song: "Read My Mind", url: "https://www.azlyrics.com/lyrics/killers/readmymind.html" },
  { artist: "Arctic Monkeys", song: "Fluorescent Adolescent", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/fluorescentadolescent.html" },
  { artist: "Muse", song: "Psycho", url: "https://www.azlyrics.com/lyrics/muse/psycho.html" },
  { artist: "Foo Fighters", song: "Best Of You", url: "https://www.azlyrics.com/lyrics/foofighters/bestofyou.html" },
  { artist: "Red Hot Chili Peppers", song: "Dani California", url: "https://www.azlyrics.com/lyrics/redhotchilipeppers/danicalifornia.html" },
  { artist: "Green Day", song: "Good Riddance (Time Of Your Life)", url: "https://www.azlyrics.com/lyrics/greenday/goodriddancetimeofyourlife.html" },
  { artist: "Blink-182", song: "All The Small Things", url: "https://www.azlyrics.com/lyrics/blink182/allthesmallthings.html" },
  { artist: "Blink-182", song: "I Miss You", url: "https://www.azlyrics.com/lyrics/blink182/imissyou.html" },
  { artist: "Sum 41", song: "Fat Lip", url: "https://www.azlyrics.com/lyrics/sum41/fatlip.html" },
  { artist: "System Of A Down", song: "Chop Suey!", url: "https://www.azlyrics.com/lyrics/systemofadown/chopsuey.html" },
  { artist: "Linkin Park", song: "What I've Done", url: "https://www.azlyrics.com/lyrics/linkinpark/whativedone.html" },
  { artist: "Linkin Park", song: "Shadow Of The Day", url: "https://www.azlyrics.com/lyrics/linkinpark/shadowoftheday.html" },
  { artist: "My Chemical Romance", song: "Helena", url: "https://www.azlyrics.com/lyrics/mychemicalromance/helena.html" },
  { artist: "Paramore", song: "Still Into You", url: "https://www.azlyrics.com/lyrics/paramore/stillintoyou.html" },
  { artist: "Fall Out Boy", song: "Thnks fr th Mmrs", url: "https://www.azlyrics.com/lyrics/falloutboy/thnksfrthmmrs.html" },

  // -------------- 408-440 (Batch 8) --------------
  { artist: "The Eagles", song: "Take It Easy", url: "https://www.azlyrics.com/lyrics/eagles/takeiteasy.html" },
  { artist: "The Eagles", song: "Desperado", url: "https://www.azlyrics.com/lyrics/eagles/desperado.html" },
  { artist: "Simon & Garfunkel", song: "The Sound Of Silence", url: "https://www.azlyrics.com/lyrics/simongarfunkel/thesoundofsilence.html" },
  { artist: "Simon & Garfunkel", song: "Bridge Over Troubled Water", url: "https://www.azlyrics.com/lyrics/simongarfunkel/bridgeovertroubledwater.html" },
  { artist: "George Harrison", song: "My Sweet Lord", url: "https://www.azlyrics.com/lyrics/georgeharrison/mysweetlord.html" },
  { artist: "John Lennon", song: "Imagine", url: "https://www.azlyrics.com/lyrics/johnlennon/imagine.html" },
  { artist: "Cat Stevens", song: "Wild World", url: "https://www.azlyrics.com/lyrics/catstevens/wildworld.html" },
  { artist: "ABBA", song: "Gimme! Gimme! Gimme! (A Man After Midnight)", url: "https://www.azlyrics.com/lyrics/abba/gimmegimmegimmeamanaftermidnight.html" },
  { artist: "ABBA", song: "Mamma Mia", url: "https://www.azlyrics.com/lyrics/abba/mammamia.html" },
  { artist: "Electric Light Orchestra", song: "Mr. Blue Sky", url: "https://www.azlyrics.com/lyrics/electriclightorchestra/mrbluesky.html" },
  { artist: "Toto", song: "Africa", url: "https://www.azlyrics.com/lyrics/toto/africa.html" },
  { artist: "A-Ha", song: "The Sun Always Shines On TV", url: "https://www.azlyrics.com/lyrics/aha/thesunalwaysshinesontv.html" },
  { artist: "Tears For Fears", song: "Everybody Wants To Rule The World", url: "https://www.azlyrics.com/lyrics/tearsforfears/everybodywantstoruletheworld.html" },
  { artist: "The Human League", song: "Don't You Want Me", url: "https://www.azlyrics.com/lyrics/humanleague/dontyouwantme.html" },
  { artist: "Culture Club", song: "Karma Chameleon", url: "https://www.azlyrics.com/lyrics/cultureclub/karmachameleon.html" },
  { artist: "The Buggles", song: "Video Killed The Radio Star", url: "https://www.azlyrics.com/lyrics/buggles/videokilledtheradiostar.html" },
  { artist: "Cher", song: "Believe", url: "https://www.azlyrics.com/lyrics/cher/believe.html" },
  { artist: "Celine Dion", song: "My Heart Will Go On", url: "https://www.azlyrics.com/lyrics/celinedion/myheartwillgoon.html" },
  { artist: "Aerosmith", song: "I Don't Want To Miss A Thing", url: "https://www.azlyrics.com/lyrics/aerosmith/idontwanttomissathing.html" },
  { artist: "Backstreet Boys", song: "Everybody (Backstreet's Back)", url: "https://www.azlyrics.com/lyrics/backstreetboys/everybodybackstreetsback.html" },
  { artist: "NSYNC", song: "It's Gonna Be Me", url: "https://www.azlyrics.com/lyrics/nsync/itsgonnabeme.html" },
  { artist: "Destiny's Child", song: "Say My Name", url: "https://www.azlyrics.com/lyrics/destinyschild/saymyname.html" },
  { artist: "Usher", song: "Burn", url: "https://www.azlyrics.com/lyrics/usher/burn.html" },
  { artist: "Lady Gaga", song: "Shallow", url: "https://www.azlyrics.com/lyrics/ladygaga/shallow.html" },
  { artist: "John Legend", song: "Love Me Now", url: "https://www.azlyrics.com/lyrics/johnlegend/lovemenow.html" },
  { artist: "Ed Sheeran", song: "Give Me Love", url: "https://www.azlyrics.com/lyrics/edsheeran/givemelove.html" },
  { artist: "Harry Styles", song: "Golden", url: "https://www.azlyrics.com/lyrics/harrystyles/golden.html" },
  { artist: "Olivia Rodrigo", song: "Deja Vu", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/dejavu.html" },
  { artist: "The Weeknd", song: "Die For You", url: "https://www.azlyrics.com/lyrics/theweeknd/dieforyou.html" },
  { artist: "Post Malone", song: "Congratulations", url: "https://www.azlyrics.com/lyrics/postmalone/congratulations.html" },
  { artist: "Drake", song: "Hold On, We're Going Home", url: "https://www.azlyrics.com/lyrics/drake/holdonweregoinghome.html" },
  { artist: "Eminem", song: "Without Me", url: "https://www.azlyrics.com/lyrics/eminem/withoutme.html" },
  { artist: "Linkin Park", song: "Faint", url: "https://www.azlyrics.com/lyrics/linkinpark/faint.html" },

  { artist: "George Michael", song: "Careless Whisper", url: "https://www.azlyrics.com/lyrics/georgemichael/carelesswhisper.html" },
  { artist: "Wham!", song: "Last Christmas", url: "https://www.azlyrics.com/lyrics/wham/lastchristmas.html" },
  { artist: "Wham!", song: "Wake Me Up Before You Go-Go", url: "https://www.azlyrics.com/lyrics/wham/wakemeupbeforeyougogo.html" },
  { artist: "Prince", song: "Purple Rain", url: "https://www.azlyrics.com/lyrics/prince/purplerain.html" },
  { artist: "Prince", song: "When Doves Cry", url: "https://www.azlyrics.com/lyrics/prince/whendovescry.html" },
  { artist: "Whitney Houston", song: "I Wanna Dance With Somebody (Who Loves Me)", url: "https://www.azlyrics.com/lyrics/whitneyhouston/iwannadancewithsomebody.html" },
  { artist: "Madonna", song: "Vogue", url: "https://www.azlyrics.com/lyrics/madonna/vogue.html" },
  { artist: "Madonna", song: "Material Girl", url: "https://www.azlyrics.com/lyrics/madonna/materialgirl.html" },
  { artist: "Bon Jovi", song: "Livin' On A Prayer", url: "https://www.azlyrics.com/lyrics/bonjovi/livinonaprayer.html" },
  { artist: "Bon Jovi", song: "It's My Life", url: "https://www.azlyrics.com/lyrics/bonjovi/itsmylife.html" },
  { artist: "Bruce Springsteen", song: "Born To Run", url: "https://www.azlyrics.com/lyrics/brucespringsteen/borntorun.html" },
  { artist: "Bruce Springsteen", song: "Dancing In The Dark", url: "https://www.azlyrics.com/lyrics/brucespringsteen/dancinginthedark.html" },
  { artist: "The Cure", song: "Just Like Heaven", url: "https://www.azlyrics.com/lyrics/cure/justlikeheaven.html" },
  { artist: "The Smiths", song: "There Is A Light That Never Goes Out", url: "https://www.azlyrics.com/lyrics/smiths/thereisalightthatnevergoesout.html" },
  { artist: "The Cranberries", song: "Zombie", url: "https://www.azlyrics.com/lyrics/cranberries/zombie.html" },
  { artist: "Soundgarden", song: "Black Hole Sun", url: "https://www.azlyrics.com/lyrics/soundgarden/blackholesun.html" },
  { artist: "Pearl Jam", song: "Alive", url: "https://www.azlyrics.com/lyrics/pearljam/alive.html" },
  { artist: "The Verve", song: "Bitter Sweet Symphony", url: "https://www.azlyrics.com/lyrics/verve/bittersweetsymphony.html" }, 
  { artist: "Oasis", song: "Supersonic", url: "https://www.azlyrics.com/lyrics/oasis/supersonic.html" },
  { artist: "Travis Scott", song: "Goosebumps", url: "https://www.azlyrics.com/lyrics/travisscott/goosebumps.html" },
  { artist: "Travis Scott", song: "Highest In The Room", url: "https://www.azlyrics.com/lyrics/travisscott/highestintheroom.html" },
  { artist: "Drake", song: "Hotline Bling", url: "https://www.azlyrics.com/lyrics/drake/hotlinebling.html" },
  { artist: "Drake", song: "In My Feelings", url: "https://www.azlyrics.com/lyrics/drake/inmyfeelings.html" },
  { artist: "Drake", song: "One Dance", url: "https://www.azlyrics.com/lyrics/drake/onedance.html" },
  { artist: "Lil Wayne", song: "A Milli", url: "https://www.azlyrics.com/lyrics/lilwayne/amilli.html" },
  { artist: "Jay-Z", song: "99 Problems", url: "https://www.azlyrics.com/lyrics/jayz/99problems.html" },
  { artist: "Jay-Z", song: "Empire State Of Mind", url: "https://www.azlyrics.com/lyrics/jayz/empirestateofmind.html" },
  { artist: "Kanye West", song: "Stronger", url: "https://www.azlyrics.com/lyrics/kanyewest/stronger.html" },
  { artist: "Kanye West", song: "Gold Digger", url: "https://www.azlyrics.com/lyrics/kanyewest/golddigger.html" },
  { artist: "Taylor Swift", song: "Cardigan", url: "https://www.azlyrics.com/lyrics/taylorswift/cardigan.html" },
  { artist: "Taylor Swift", song: "Willow", url: "https://www.azlyrics.com/lyrics/taylorswift/willow.html" },
  { artist: "Olivia Rodrigo", song: "Drivers License", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/driverslicense.html" },
  { artist: "Olivia Rodrigo", song: "Good 4 U", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/good4u.html" },
  { artist: "Doja Cat", song: "Need To Know", url: "https://www.azlyrics.com/lyrics/dojacat/needtoknow.html" },
  { artist: "Doja Cat", song: "Woman", url: "https://www.azlyrics.com/lyrics/dojacat/woman.html" },
  { artist: "Harry Styles", song: "Adore You", url: "https://www.azlyrics.com/lyrics/harrystyles/adoreyou.html" },
  { artist: "Harry Styles", song: "Falling", url: "https://www.azlyrics.com/lyrics/harrystyles/falling.html" },
  { artist: "The Weeknd", song: "I Feel It Coming", url: "https://www.azlyrics.com/lyrics/weeknd/ifeelitcoming.html" },
  { artist: "Billie Eilish", song: "Ocean Eyes", url: "https://www.azlyrics.com/lyrics/billieeilish/oceaneyes.html" },
  { artist: "Billie Eilish", song: "Happier Than Ever", url: "https://www.azlyrics.com/lyrics/billieeilish/happierthanever.html" },
  { artist: "Lil Nas X", song: "Industry Baby", url: "https://www.azlyrics.com/lyrics/lilnasx/industrybaby.html" },
  { artist: "Megan Thee Stallion", song: "Savage", url: "https://www.azlyrics.com/lyrics/megantheestallion/savage.html" },
  { artist: "Cardi B", song: "WAP", url: "https://www.azlyrics.com/lyrics/cardib/wap.html" },
  { artist: "Lizzo", song: "Truth Hurts", url: "https://www.azlyrics.com/lyrics/lizzo/truthhurts.html" },
  { artist: "Halsey", song: "Without Me", url: "https://www.azlyrics.com/lyrics/halsey/withoutme.html" },
  { artist: "Shawn Mendes", song: "Señorita", url: "https://www.azlyrics.com/lyrics/shawnmendes/senorita.html" },
  { artist: "Zayn", song: "I Don't Wanna Live Forever", url: "https://www.azlyrics.com/lyrics/zayn/idontwannaliveforever.html" },
  { artist: "Justin Timberlake", song: "Cry Me A River", url: "https://www.azlyrics.com/lyrics/justintimberlake/crymeariver.html" },
  { artist: "Justin Timberlake", song: "SexyBack", url: "https://www.azlyrics.com/lyrics/justintimberlake/sexyback.html" },
  { artist: "Christina Aguilera", song: "Dirrty", url: "https://www.azlyrics.com/lyrics/christinaaguilera/dirrty.html" },
  { artist: "Avril Lavigne", song: "Sk8er Boi", url: "https://www.azlyrics.com/lyrics/avrillavigne/sk8erboi.html" },
  { artist: "Avril Lavigne", song: "Girlfriend", url: "https://www.azlyrics.com/lyrics/avrillavigne/girlfriend.html" },
  { artist: "Muse", song: "Starlight", url: "https://www.azlyrics.com/lyrics/muse/starlight.html" },
  { artist: "Muse", song: "Time Is Running Out", url: "https://www.azlyrics.com/lyrics/muse/timeisrunningout.html" },
  { artist: "Arctic Monkeys", song: "Do I Wanna Know?", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/doiwannaknow.html" },
  { artist: "Arctic Monkeys", song: "505", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/505.html" },
  { artist: "Gorillaz", song: "Feel Good Inc.", url: "https://www.azlyrics.com/lyrics/gorillaz/feelgoodinc.html" },
  { artist: "Gorillaz", song: "Clint Eastwood", url: "https://www.azlyrics.com/lyrics/gorillaz/clinteastwood.html" },
  { artist: "Jamiroquai", song: "Virtual Insanity", url: "https://www.azlyrics.com/lyrics/jamiroquai/virtualinsanity.html" },
  { artist: "The Fugees", song: "Killing Me Softly", url: "https://www.azlyrics.com/lyrics/fugees/killingmesoftly.html" },
  { artist: "Sublime", song: "Santeria", url: "https://www.azlyrics.com/lyrics/sublime/santeria.html" },
  { artist: "Smash Mouth", song: "All Star", url: "https://www.azlyrics.com/lyrics/smashmouth/allstar.html" },
  { artist: "Goo Goo Dolls", song: "Iris", url: "https://www.azlyrics.com/lyrics/googoodolls/iris.html" },
  { artist: "Third Eye Blind", song: "Jumper", url: "https://www.azlyrics.com/lyrics/thirdeyeblind/jumper.html" },
  { artist: "Radiohead", song: "Karma Police", url: "https://www.azlyrics.com/lyrics/radiohead/karmapolice.html" },
  { artist: "Jeff Buckley", song: "Hallelujah", url: "https://www.azlyrics.com/lyrics/jeffbuckley/hallelujah.html" },
  { artist: "Leonard Cohen", song: "Hallelujah", url: "https://www.azlyrics.com/lyrics/leonardcohen/hallelujah.html" },
  { artist: "Nat King Cole", song: "Unforgettable", url: "https://www.azlyrics.com/lyrics/natkingcole/unforgettable.html" },
  { artist: "Frank Sinatra", song: "My Way", url: "https://www.azlyrics.com/lyrics/franksinatra/myway.html" },
  { artist: "Frank Sinatra", song: "New York, New York", url: "https://www.azlyrics.com/lyrics/franksinatra/newyorknewyork.html" },
  { artist: "Louis Armstrong", song: "What A Wonderful World", url: "https://www.azlyrics.com/lyrics/louisarmstrong/whatawonderfulworld.html" },
  { artist: "Ray Charles", song: "Georgia On My Mind", url: "https://www.azlyrics.com/lyrics/raycharles/georgiaonmymind.html" },
  { artist: "Etta James", song: "At Last", url: "https://www.azlyrics.com/lyrics/ettajames/atlast.html" },
  { artist: "Aretha Franklin", song: "Respect", url: "https://www.azlyrics.com/lyrics/arethafranklin/respect.html" },
  { artist: "Marvin Gaye", song: "What's Going On", url: "https://www.azlyrics.com/lyrics/marvingaye/whatsgoingon.html" },
  { artist: "The Temptations", song: "My Girl", url: "https://www.azlyrics.com/lyrics/temptations/mygirl.html" },
  { artist: "Stevie Wonder", song: "Superstition", url: "https://www.azlyrics.com/lyrics/steviewonder/superstition.html" },
  { artist: "Earth, Wind & Fire", song: "September", url: "https://www.azlyrics.com/lyrics/earthwindfire/september.html" },
  { artist: "Bee Gees", song: "Stayin' Alive", url: "https://www.azlyrics.com/lyrics/beegees/stayinalive.html" },
  { artist: "Gloria Gaynor", song: "I Will Survive", url: "https://www.azlyrics.com/lyrics/gloriagaynor/iwillsurvive.html" },

  // -------------- 308-407 (Batch 7) --------------
  { artist: "Michael Jackson", song: "The Way You Make Me Feel", url: "https://www.azlyrics.com/lyrics/michaeljackson/thewayyoumakemefeel.html" },
  { artist: "Michael Jackson", song: "Black Or White", url: "https://www.azlyrics.com/lyrics/michaeljackson/blackorwhite.html" },
  { artist: "Prince", song: "Kiss", url: "https://www.azlyrics.com/lyrics/prince/kiss.html" },
  { artist: "Prince", song: "Raspberry Beret", url: "https://www.azlyrics.com/lyrics/prince/raspberryberet.html" },
  { artist: "Madonna", song: "Like A Virgin", url: "https://www.azlyrics.com/lyrics/madonna/likeavirgin.html" },
  { artist: "Madonna", song: "Hung Up", url: "https://www.azlyrics.com/lyrics/madonna/hungup.html" },
  { artist: "U2", song: "Where The Streets Have No Name", url: "https://www.azlyrics.com/lyrics/u2/wherethestreetshavenoname.html" },
  { artist: "U2", song: "Sunday Bloody Sunday", url: "https://www.azlyrics.com/lyrics/u2/sundaybloodysunday.html" },
  { artist: "U2", song: "One", url: "https://www.azlyrics.com/lyrics/u2/one.html" },
  { artist: "REM", song: "Everybody Hurts", url: "https://www.azlyrics.com/lyrics/rem/everybodyhurts.html" },
  { artist: "REM", song: "Man On The Moon", url: "https://www.azlyrics.com/lyrics/rem/manonthemoon.html" },
  { artist: "The Smiths", song: "Heaven Knows I'm Miserable Now", url: "https://www.azlyrics.com/lyrics/smiths/heavenknowsimmiserablenow.html" },
  { artist: "Depeche Mode", song: "Enjoy The Silence", url: "https://www.azlyrics.com/lyrics/depechemode/enjoythesilence.html" },
  { artist: "Depeche Mode", song: "Personal Jesus", url: "https://www.azlyrics.com/lyrics/depechemode/personaljesus.html" },
  { artist: "The Cure", song: "Close To Me", url: "https://www.azlyrics.com/lyrics/cure/closetome.html" },
  { artist: "New Order", song: "Blue Monday", url: "https://www.azlyrics.com/lyrics/neworder/bluemonday.html" },
  { artist: "The Clash", song: "London Calling", url: "https://www.azlyrics.com/lyrics/clash/londoncalling.html" },
  { artist: "The Clash", song: "Should I Stay Or Should I Go", url: "https://www.azlyrics.com/lyrics/clash/shouldistayorshouldigo.html" },
  { artist: "The Velvet Underground", song: "Sweet Jane", url: "https://www.azlyrics.com/lyrics/velvetunderground/sweetjane.html" },
  { artist: "The Doors", song: "Light My Fire", url: "https://www.azlyrics.com/lyrics/doors/lightmyfire.html" },
  { artist: "The Doors", song: "Riders On The Storm", url: "https://www.azlyrics.com/lyrics/doors/ridersonthestorm.html" },
  { artist: "Jimi Hendrix", song: "Purple Haze", url: "https://www.azlyrics.com/lyrics/jimihendrix/purplehaze.html" },
  { artist: "Jimi Hendrix", song: "All Along The Watchtower", url: "https://www.azlyrics.com/lyrics/jimihendrix/allalongthewatchtower.html" },
  { artist: "Janis Joplin", song: "Me And Bobby McGee", url: "https://www.azlyrics.com/lyrics/janisjoplin/meandbobbymcgee.html" },
  { artist: "The Who", song: "Baba O'Riley", url: "https://www.azlyrics.com/lyrics/who/babaoriley.html" },
  { artist: "The Kinks", song: "Lola", url: "https://www.azlyrics.com/lyrics/kinks/lola.html" },
  { artist: "The Monkees", song: "I'm A Believer", url: "https://www.azlyrics.com/lyrics/monkees/imabeliever.html" },
  { artist: "Dusty Springfield", song: "Son Of A Preacher Man", url: "https://www.azlyrics.com/lyrics/dustyspringfield/sonofapreacherman.html" },
  { artist: "Aretha Franklin", song: "Natural Woman", url: "https://www.azlyrics.com/lyrics/arethafranklin/naturalwoman.html" },
  { artist: "Otis Redding", song: "(Sittin' On) The Dock Of The Bay", url: "https://www.azlyrics.com/lyrics/otisredding/sittinonthedockofthebay.html" },
  { artist: "Sam Cooke", song: "A Change Is Gonna Come", url: "https://www.azlyrics.com/lyrics/samcooke/achangeisgonnacome.html" },
  { artist: "The Supremes", song: "You Can't Hurry Love", url: "https://www.azlyrics.com/lyrics/supremes/youcanthurrylove.html" },
  { artist: "Marvin Gaye", song: "Sexual Healing", url: "https://www.azlyrics.com/lyrics/marvingaye/sexualhealing.html" },
  { artist: "Tina Turner", song: "What's Love Got To Do With It", url: "https://www.azlyrics.com/lyrics/tinaturner/whatslovegottodowithit.html" },
  { artist: "Amy Winehouse", song: "Valerie", url: "https://www.azlyrics.com/lyrics/amywinehouse/valerie.html" },
  { artist: "Adele", song: "Skyfall", url: "https://www.azlyrics.com/lyrics/adele/skyfall.html" },
  { artist: "Sam Smith", song: "Writing's On The Wall", url: "https://www.azlyrics.com/lyrics/samsmith/writingsonthewall.html" },
  { artist: "Sia", song: "The Greatest", url: "https://www.azlyrics.com/lyrics/sia/thegreatest.html" },
  { artist: "Billie Eilish", song: "Therefore I Am", url: "https://www.azlyrics.com/lyrics/billieeilish/thereforeiam.html" },
  { artist: "Lil Nas X", song: "That's What I Want", url: "https://www.azlyrics.com/lyrics/lilnasx/thatswhatiwant.html" },
  { artist: "Doja Cat", song: "Streets", url: "https://www.azlyrics.com/lyrics/dojacat/streets.html" },
  { artist: "Megan Thee Stallion", song: "Body", url: "https://www.azlyrics.com/lyrics/megantheestallion/body.html" },
  { artist: "Cardi B", song: "Bodak Yellow", url: "https://www.azlyrics.com/lyrics/cardib/bodakyellow.html" },
  { artist: "Kendrick Lamar", song: "Money Trees", url: "https://www.azlyrics.com/lyrics/kendricklamar/moneytrees.html" },
  { artist: "Travis Scott", song: "Antidote", url: "https://www.azlyrics.com/lyrics/travisscott/antidote.html" },
  { artist: "Drake", song: "Take Care", url: "https://www.azlyrics.com/lyrics/drake/takecare.html" },
  { artist: "Drake", song: "Started From The Bottom", url: "https://www.azlyrics.com/lyrics/drake/startedfromthebottom.html" },
  { artist: "Post Malone", song: "White Iverson", url: "https://www.azlyrics.com/lyrics/postmalone/whiteiverson.html" },
  { artist: "Ed Sheeran", song: "The A Team", url: "https://www.azlyrics.com/lyrics/edsheeran/theateam.html" },
  { artist: "Ed Sheeran", song: "Lego House", url: "https://www.azlyrics.com/lyrics/edsheeran/legohouse.html" },
  { artist: "Avicii", song: "Levels", url: "https://www.azlyrics.com/lyrics/avicii/levels.html" },
  { artist: "Avicii", song: "Hey Brother", url: "https://www.azlyrics.com/lyrics/avicii/heybrother.html" },
  { artist: "The Chainsmokers", song: "Don't Let Me Down", url: "https://www.azlyrics.com/lyrics/chainsmokers/dontletmedown.html" },
  { artist: "Marshmello", song: "Happier", url: "https://www.azlyrics.com/lyrics/marshmello/happier.html" },
  { artist: "Alan Walker", song: "Faded", url: "https://www.azlyrics.com/lyrics/alanwalker/faded.html" },
  { artist: "Kygo", song: "Firestone", url: "https://www.azlyrics.com/lyrics/kygo/firestone.html" },
  { artist: "Jonas Brothers", song: "Sucker", url: "https://www.azlyrics.com/lyrics/jonasbrothers/sucker.html" },
  { artist: "5 Seconds Of Summer", song: "Youngblood", url: "https://www.azlyrics.com/lyrics/5secondsofsummer/youngblood.html" },
  { artist: "One Direction", song: "What Makes You Beautiful", url: "https://www.azlyrics.com/lyrics/onedirection/whatmakesyoubeautiful.html" },
  { artist: "One Direction", song: "Story Of My Life", url: "https://www.azlyrics.com/lyrics/onedirection/storyofmylife.html" },
  { artist: "Demi Lovato", song: "Skyscraper", url: "https://www.azlyrics.com/lyrics/demilovato/skyscraper.html" },
  { artist: "Selena Gomez", song: "Come & Get It", url: "https://www.azlyrics.com/lyrics/selenagomez/comegetit.html" },
  { artist: "Miley Cyrus", song: "Wrecking Ball", url: "https://www.azlyrics.com/lyrics/mileycyrus/wreckingball.html" },
  { artist: "Miley Cyrus", song: "Party In The U.S.A.", url: "https://www.azlyrics.com/lyrics/mileycyrus/partyintheusa.html" },
  { artist: "Bruno Mars", song: "When I Was Your Man", url: "https://www.azlyrics.com/lyrics/brunomars/wheniwasyourman.html" },
  { artist: "Bruno Mars", song: "Locked Out Of Heaven", url: "https://www.azlyrics.com/lyrics/brunomars/lockedoutofheaven.html" },
  { artist: "Adele", song: "Water Under The Bridge", url: "https://www.azlyrics.com/lyrics/adele/waterunderthebridge.html" },
  { artist: "John Legend", song: "Ordinary People", url: "https://www.azlyrics.com/lyrics/johnlegend/ordinarypeople.html" },
  { artist: "Sam Smith", song: "Too Good At Goodbyes", url: "https://www.azlyrics.com/lyrics/samsmith/toogoodatgoodbyes.html" },
  { artist: "Coldplay", song: "A Sky Full Of Stars", url: "https://www.azlyrics.com/lyrics/coldplay/askyfullofstars.html" },
  { artist: "Imagine Dragons", song: "Thunder", url: "https://www.azlyrics.com/lyrics/imaginedragons/thunder.html" },
  { artist: "The Killers", song: "Read My Mind", url: "https://www.azlyrics.com/lyrics/killers/readmymind.html" },
  { artist: "Arctic Monkeys", song: "Fluorescent Adolescent", url: "https://www.azlyrics.com/lyrics/arcticmonkeys/fluorescentadolescent.html" },
  { artist: "Muse", song: "Psycho", url: "https://www.azlyrics.com/lyrics/muse/psycho.html" },
  { artist: "Foo Fighters", song: "Best Of You", url: "https://www.azlyrics.com/lyrics/foofighters/bestofyou.html" },
  { artist: "Red Hot Chili Peppers", song: "Dani California", url: "https://www.azlyrics.com/lyrics/redhotchilipeppers/danicalifornia.html" },
  { artist: "Green Day", song: "Good Riddance (Time Of Your Life)", url: "https://www.azlyrics.com/lyrics/greenday/goodriddance.html" },
  { artist: "Blink-182", song: "All The Small Things", url: "https://www.azlyrics.com/lyrics/blink182/allthesmallthings.html" },
  { artist: "Blink-182", song: "I Miss You", url: "https://www.azlyrics.com/lyrics/blink182/imissyou.html" },
  { artist: "Sum 41", song: "Fat Lip", url: "https://www.azlyrics.com/lyrics/sum41/fatlip.html" },
  { artist: "System Of A Down", song: "Chop Suey!", url: "https://www.azlyrics.com/lyrics/systemofadown/chopsuey.html" },
  { artist: "Linkin Park", song: "What I've Done", url: "https://www.azlyrics.com/lyrics/linkinpark/whativedone.html" },
  { artist: "Linkin Park", song: "Shadow Of The Day", url: "https://www.azlyrics.com/lyrics/linkinpark/shadowoftheday.html" },
  { artist: "My Chemical Romance", song: "Helena", url: "https://www.azlyrics.com/lyrics/mychemicalromance/helena.html" },
  { artist: "Paramore", song: "Still Into You", url: "https://www.azlyrics.com/lyrics/paramore/stillintoyou.html" },
  { artist: "Fall Out Boy", song: "Thnks fr th Mmrs", url: "https://www.azlyrics.com/lyrics/falloutboy/thnksfrthmmrs.html" },

  // --------------  408-440 (Batch 8) --------------
  { artist: "The Eagles", song: "Take It Easy", url: "https://www.azlyrics.com/lyrics/eagles/takeiteasy.html" },
  { artist: "The Eagles", song: "Desperado", url: "https://www.azlyrics.com/lyrics/eagles/desperado.html" },
  { artist: "Simon & Garfunkel", song: "The Sound Of Silence", url: "https://www.azlyrics.com/lyrics/simongarfunkel/thesoundofsilence.html" },
  { artist: "Simon & Garfunkel", song: "Bridge Over Troubled Water", url: "https://www.azlyrics.com/lyrics/simongarfunkel/bridgeovertroubledwater.html" },
  { artist: "George Harrison", song: "My Sweet Lord", url: "https://www.azlyrics.com/lyrics/georgeharrison/mysweetlord.html" },
  { artist: "John Lennon", song: "Imagine", url: "https://www.azlyrics.com/lyrics/johnlennon/imagine.html" },
  { artist: "Cat Stevens", song: "Wild World", url: "https://www.azlyrics.com/lyrics/catstevens/wildworld.html" },
  { artist: "ABBA", song: "Gimme! Gimme! Gimme! (A Man After Midnight)", url: "https://www.azlyrics.com/lyrics/abba/gimmegimmegimme.html" },
  { artist: "ABBA", song: "Mamma Mia", url: "https://www.azlyrics.com/lyrics/abba/mammamia.html" },
  { artist: "Electric Light Orchestra", song: "Mr. Blue Sky", url: "https://www.azlyrics.com/lyrics/electriclightorchestra/mrbluesky.html" },
  { artist: "Toto", song: "Africa", url: "https://www.azlyrics.com/lyrics/toto/africa.html" },
  { artist: "A-Ha", song: "The Sun Always Shines On TV", url: "https://www.azlyrics.com/lyrics/aha/thesunalwaysshinesontv.html" },
  { artist: "Tears For Fears", song: "Everybody Wants To Rule The World", url: "https://www.azlyrics.com/lyrics/tearsforfears/everybodywantstoruletheworld.html" },
  { artist: "The Human League", song: "Don't You Want Me", url: "https://www.azlyrics.com/lyrics/humanleague/dontyouwantme.html" },
  { artist: "Culture Club", song: "Karma Chameleon", url: "https://www.azlyrics.com/lyrics/cultureclub/karmachameleon.html" },
  { artist: "The Buggles", song: "Video Killed The Radio Star", url: "https://www.azlyrics.com/lyrics/buggles/videokilledtheradiostar.html" },
  { artist: "Cher", song: "Believe", url: "https://www.azlyrics.com/lyrics/cher/believe.html" },
  { artist: "Celine Dion", song: "My Heart Will Go On", url: "https://www.azlyrics.com/lyrics/celinedion/myheartwillgoon.html" },
  { artist: "Aerosmith", song: "I Don't Want To Miss A Thing", url: "https://www.azlyrics.com/lyrics/aerosmith/idontwanttomissathing.html" },
  { artist: "Backstreet Boys", song: "Everybody (Backstreet's Back)", url: "https://www.azlyrics.com/lyrics/backstreetboys/everybodybackstreetsback.html" },
  { artist: "NSYNC", song: "It's Gonna Be Me", url: "https://www.azlyrics.com/lyrics/nsync/itsgonnabeme.html" },
  { artist: "Destiny's Child", song: "Say My Name", url: "https://www.azlyrics.com/lyrics/destinyschild/saymyname.html" },
  { artist: "Usher", song: "Burn", url: "https://www.azlyrics.com/lyrics/usher/burn.html" },
  { artist: "Lady Gaga", song: "Shallow", url: "https://www.azlyrics.com/lyrics/ladygaga/shallow.html" },
  { artist: "John Legend", song: "Love Me Now", url: "https://www.azlyrics.com/lyrics/johnlegend/lovemenow.html" },
  { artist: "Ed Sheeran", song: "Give Me Love", url: "https://www.azlyrics.com/lyrics/edsheeran/givemelove.html" },
  { artist: "Harry Styles", song: "Golden", url: "https://www.azlyrics.com/lyrics/harrystyles/golden.html" },
  { artist: "Olivia Rodrigo", song: "Deja Vu", url: "https://www.azlyrics.com/lyrics/oliviarodrigo/dejavu.html" },
  { artist: "The Weeknd", song: "Die For You", url: "https://www.azlyrics.com/lyrics/theweeknd/dieforyou.html" },
  { artist: "Post Malone", song: "Congratulations", url: "https://www.azlyrics.com/lyrics/postmalone/congratulations.html" },
  { artist: "Drake", song: "Hold On, We're Going Home", url: "https://www.azlyrics.com/lyrics/drake/holdonweregoinghome.html" },
  { artist: "Eminem", song: "Without Me", url: "https://www.azlyrics.com/lyrics/eminem/withoutme.html" },
  { artist: "Linkin Park", song: "Faint", url: "https://www.azlyrics.com/lyrics/linkinpark/faint.html" }
];


// Use example:
// runAllFetches(fullAZLyricsLinks, fetchSongLyrics);

module.exports = { runAllFetches };